import type { InsertProduct } from "@shared/schema";

export const catalogProducts: Omit<InsertProduct, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // PTx Trimble Products
  {
    name: "GFX-1260 Display",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Displays",
    tagline: "Premium 12.1-inch display for precision agriculture operations",
    shortDescription: "Advanced 12.1-inch display for controlling and executing precision agriculture operations.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/displays/gfx-1260-display",
    highlights: ["Large 12.1-inch touchscreen", "Android-based platform", "Precision-IQ compatible"],
    keyFeatures: ["Android-based", "Precision-IQ platform", "High-definition display"],
    specs: [],
    worksWith: ["NAV-960", "NAV-500", "Autopilot systems"],
    slug: "ptx-gfx-1260",
  },
  {
    name: "GFX-1060 Display",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Displays",
    tagline: "10-inch Android-based display for precision agriculture",
    shortDescription: "10-inch Android-based display for controlling and executing operations using the Precision-IQ platform.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/displays/gfx-1060-display",
    highlights: ["Android-based", "Precision-IQ platform", "ISOBUS compatible"],
    keyFeatures: ["Android-based", "Precision-IQ platform"],
    specs: [
      "10-inch high-definition color touchscreen",
      "Android-based operating system",
      "Precision-IQ firmware",
      "32 GB storage / 4 GB RAM",
      "Optional ISOBUS task controller & universal terminal",
      "Control up to 6 input channels and 255 sections",
    ],
    worksWith: ["NAV-960", "NAV-500", "Field-IQ"],
    slug: "ptx-gfx-1060",
  },
  {
    name: "GFX-350 Display",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Displays",
    tagline: "Compact 7-inch display for essential guidance functions",
    shortDescription: "Entry-level display for basic guidance and application control.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/displays/gfx-350-display",
    highlights: ["Compact 7-inch screen", "Cost-effective solution", "Easy to use"],
    keyFeatures: ["Compact design", "Essential features"],
    specs: [],
    worksWith: ["EZ-Pilot Pro", "NAV-500"],
    slug: "ptx-gfx-350",
  },
  {
    name: "NAV-960 Guidance Controller",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Guidance Controllers",
    tagline: "High-accuracy GNSS guidance controller",
    shortDescription: "Premium guidance controller with centimeter-level accuracy.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/guidance-control/nav-960-guidance-controller",
    highlights: ["Centimeter-level accuracy", "Multi-constellation GNSS", "Integrated INS"],
    keyFeatures: ["High-accuracy positioning", "Integrated inertial system"],
    specs: [],
    worksWith: ["GFX-1260", "GFX-1060", "Autopilot"],
    slug: "ptx-nav-960",
  },
  {
    name: "NAV-500 Guidance Controller",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Guidance Controllers",
    tagline: "Reliable mid-range GNSS guidance controller",
    shortDescription: "Cost-effective guidance controller for precision agriculture.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/guidance-control/nav-500-guidance-controller",
    highlights: ["Reliable accuracy", "Multi-constellation support", "Affordable"],
    keyFeatures: ["Multi-constellation GNSS", "Reliable performance"],
    specs: [],
    worksWith: ["GFX-1060", "GFX-350", "EZ-Pilot Pro"],
    slug: "ptx-nav-500",
  },
  {
    name: "AG-392 Receiver",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Receivers",
    tagline: "Multi-frequency GNSS receiver for precision guidance",
    shortDescription: "High-performance receiver supporting multiple correction sources.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/guidance-control/ag-392-receiver",
    highlights: ["Multi-frequency tracking", "Multiple correction sources", "Reliable performance"],
    keyFeatures: ["Multi-frequency GNSS", "RTK capable"],
    specs: [],
    worksWith: ["GFX displays", "Guidance controllers"],
    slug: "ptx-ag-392",
  },
  {
    name: "R750 Modular GNSS Receiver",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Receivers",
    tagline: "Next-generation modular GNSS receiver",
    shortDescription: "Flexible modular receiver with advanced positioning capabilities.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/guidance-control/r750-modular-gnss-receiver",
    highlights: ["Modular design", "Future-proof technology", "High accuracy"],
    keyFeatures: ["Modular architecture", "Advanced GNSS tracking"],
    specs: [],
    worksWith: ["GFX displays", "NAV controllers"],
    slug: "ptx-r750",
  },
  {
    name: "Autopilot Automated Steering",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Steering Systems",
    tagline: "Full-featured automated steering system",
    shortDescription: "Complete hands-free steering solution for maximum productivity.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/steering-systems/autopilot-automated-steering",
    highlights: ["Hands-free operation", "Sub-inch accuracy", "All-terrain capability"],
    keyFeatures: ["Automated steering", "High precision"],
    specs: [],
    worksWith: ["NAV-960", "GFX-1260", "GFX-1060"],
    slug: "ptx-autopilot-automated",
  },
  {
    name: "Autopilot Motor Drive",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Steering Systems",
    tagline: "Motor-driven automated steering for older equipment",
    shortDescription: "Retrofit steering solution using motor-driven wheel control.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/steering-systems/autopilot-motor-drive",
    highlights: ["Retrofit compatible", "Easy installation", "Reliable performance"],
    keyFeatures: ["Motor-driven control", "Legacy equipment support"],
    specs: [],
    worksWith: ["NAV controllers", "GFX displays"],
    slug: "ptx-autopilot-motor-drive",
  },
  {
    name: "EZ-Pilot Pro Steering",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Steering Systems",
    tagline: "Affordable assisted steering solution",
    shortDescription: "Entry-level assisted steering for cost-conscious operations.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/steering-systems/ez-pilot-pro-steering",
    highlights: ["Affordable option", "Easy installation", "Reliable guidance"],
    keyFeatures: ["Assisted steering", "Budget-friendly"],
    specs: [],
    worksWith: ["GFX-350", "NAV-500"],
    slug: "ptx-ez-pilot-pro",
  },
  {
    name: "TrueTracker Implement Steering",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Steering Systems",
    tagline: "Active implement steering for perfect row alignment",
    shortDescription: "Keeps implements precisely on the guidance line regardless of field conditions.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/steering-systems/truetracker-implement-steering-system",
    highlights: ["Active implement control", "Reduces skips and overlaps", "Works on hillsides"],
    keyFeatures: ["Implement guidance", "Active steering"],
    specs: [],
    worksWith: ["Autopilot", "NAV-960"],
    slug: "ptx-truetracker",
  },
  {
    name: "Field-IQ Crop Input Control",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Application Control",
    tagline: "Complete crop input management system",
    shortDescription: "Manages flow and application to prevent overlap, control rate, monitor delivery/blockage, and automate spreading controls.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/flow-application-control/field-iq-crop-input-control-system",
    highlights: ["Section control", "Variable rate", "Blockage monitoring"],
    keyFeatures: ["Flow management", "Overlap prevention"],
    specs: [],
    worksWith: ["GFX displays", "Planters", "Sprayers"],
    slug: "ptx-field-iq-crop-input",
  },
  {
    name: "WeedSeeker 2 Spot Spray",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Application Control",
    tagline: "See-and-spray weed detection system",
    shortDescription: "Real-time weed detection and targeted application to reduce chemical use.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/flow-application-control/weedseeker-2-spot-spray-system",
    highlights: ["90% chemical savings", "Real-time detection", "Fallow field application"],
    keyFeatures: ["Optical sensing", "Targeted spraying"],
    specs: [],
    worksWith: ["Sprayers", "GFX displays"],
    slug: "ptx-weedseeker-2",
  },
  {
    name: "Field-IQ ISOBUS Liquid Control",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Application Control",
    tagline: "ISOBUS-compatible liquid application control",
    shortDescription: "Universal liquid control system with ISOBUS compatibility.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/flow-application-control/field-iq-isobus-liquid-control-system",
    highlights: ["ISOBUS compatible", "Universal connectivity", "Precise control"],
    keyFeatures: ["ISOBUS protocol", "Liquid application"],
    specs: [],
    worksWith: ["ISOBUS implements", "GFX displays"],
    slug: "ptx-field-iq-isobus-liquid",
  },
  {
    name: "WM-FieldForm",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Land Forming",
    tagline: "Precision land forming and leveling system",
    shortDescription: "Automated grade control for efficient land forming operations.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/land-forming/wm-fieldform",
    highlights: ["Automated grading", "Precision leveling", "Improved drainage"],
    keyFeatures: ["Grade control", "Land forming automation"],
    specs: [],
    worksWith: ["Scrapers", "Land planes"],
    slug: "ptx-wm-fieldform",
  },
  {
    name: "VerticalPoint RTK Grade Control",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Land Forming",
    tagline: "RTK-based grade control for land leveling",
    shortDescription: "High-precision RTK grade control for land forming applications.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/land-forming/verticalpoint-rtk-grade-control",
    highlights: ["RTK precision", "Vertical accuracy", "Real-time control"],
    keyFeatures: ["RTK positioning", "Grade control"],
    specs: [],
    worksWith: ["Land forming equipment", "GFX displays"],
    slug: "ptx-verticalpoint-rtk",
  },
  {
    name: "WM-Drain Solution",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Subsurface Drainage",
    tagline: "Complete subsurface drainage solution",
    shortDescription: "Integrated drainage installation guidance and control system.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/subsurface-drainage/wm-drain-solution",
    highlights: ["Precision installation", "Grade control", "Drainage planning"],
    keyFeatures: ["Drainage guidance", "Installation control"],
    specs: [],
    worksWith: ["Tile plows", "GFX displays"],
    slug: "ptx-wm-drain-solution",
  },
  {
    name: "FarmENGAGE",
    brand: "PTx Trimble",
    equipment: "Software",
    category: "Software",
    tagline: "Farm operations management platform",
    shortDescription: "Farm operations management software focused on fleet connectivity and operational control.",
    oemUrl: "https://www.ptxag.com/en/farmengage/",
    highlights: ["Fleet management", "Real-time monitoring", "Operations analytics"],
    keyFeatures: ["Fleet connectivity", "Operational control"],
    specs: [],
    worksWith: ["All PTx Trimble hardware"],
    slug: "ptx-farmengage",
  },

  // XAG Products
  {
    name: "P150 Max Agricultural Drone",
    brand: "XAG",
    equipment: "Drone",
    category: "Drones",
    tagline: "Push Efficiency to the New Limit",
    shortDescription: "State-of-the-art agricultural drone designed for superior efficiency with 80kg payload, 80L tank, autonomous spraying, spreading, field mapping, and material transport at up to 20 m/s flight speed.",
    oemUrl: "https://xa.com/en/p150max",
    highlights: ["80 kg max payload", "80 L smart liquid tank", "115 L granule container", "20 m/s flight speed", "4D imaging radar obstacle avoidance", "Map-free 3D flight mode"],
    keyFeatures: ["RevoSpray5 spraying system", "RevoCast5 spreading", "RealTerra field mapping", "SuperX 5 Ultra intelligent control", "PPP-AR positioning", "7-minute rapid charging"],
    specs: ["Max Payload: 80 kg", "Max Flight Speed: 20 m/s", "Smart Liquid Tank: 80 L", "Max Flow Rate: 46 L/min", "Effective Spray Width: 5-10 m", "Granule Container: 115 L", "Max Spread Rate: 300 kg/min", "Effective Spread Width: 9 m", "Sensing Range: 1.5-100 m"],
    worksWith: ["XAG One App", "SRC 5 Remote Controller", "XRTK 7 Mobile Station", "B141050 Battery"],
    slug: "xag-p150-max",
  },
  {
    name: "P150 Agricultural Drone",
    brand: "XAG",
    equipment: "Drone",
    category: "Drones",
    tagline: "The Next-Level Efficiency",
    shortDescription: "Ultimate agricultural drone designed for spraying, spreading, and field mapping with 70kg maximum payload, helping you farm more sustainably and optimize inputs.",
    oemUrl: "https://xa.com/en/p150",
    highlights: ["70 kg max payload", "60 L smart liquid tank", "115 L granule container", "18 m/s flight speed", "4D imaging radar", "Real-time 3D terrain mapping"],
    keyFeatures: ["RevoSpray4 system", "RevoCast4 spreading", "RealTerra 3 mapping", "SuperX 5 Pro control", "Variable-rate application", "Swarm operation"],
    specs: ["Max Payload: 70 kg", "Max Flight Speed: 18 m/s", "Smart Liquid Tank: 60 L", "Max Flow Rate: 30 L/min", "Effective Spray Width: 5-10 m", "Granule Container: 115 L", "Max Spread Rate: 280 kg/min", "Spraying Efficiency: 26 ha/h"],
    worksWith: ["XAG One App", "SRC4 Remote Controller", "ACS4 Control Stick", "XRTK6 Pro Station"],
    slug: "xag-p150",
  },
  {
    name: "P60 Agricultural Drone",
    brand: "XAG",
    equipment: "Drone",
    category: "Drones",
    tagline: "Small But Mighty",
    shortDescription: "Flexible, cost-effective solution for spraying, spreading and field mapping. Designed for autonomous farm operation with unmatched precision and advanced intelligence.",
    oemUrl: "https://xa.com/en/p60",
    highlights: ["30 kg max payload", "30 L smart liquid tank", "45 L granule container", "13.8 m/s flight speed", "One-person operation", "Compact design"],
    keyFeatures: ["RevoSpray4 system", "RevoCast4 spreading", "RealTerra 3 mapping", "SuperX 5 Pro control", "IPX6K protection", "Foldable arms"],
    specs: ["Max Payload: 30 kg", "Max Flight Speed: 13.8 m/s", "Smart Liquid Tank: 30 L", "Max Flow Rate: 30 L/min", "Effective Spray Width: 5-10 m", "Granule Container: 45 L", "Max Spread Rate: 190 kg/min", "Spraying Efficiency: 13.5 ha/h"],
    worksWith: ["XAG One App", "SRC4 Remote Controller", "ACS4 Control Stick", "DL1 Data Link"],
    slug: "xag-p60",
  },
  {
    name: "P100 Pro Agricultural Drone",
    brand: "XAG",
    equipment: "Drone",
    category: "Drones",
    tagline: "Pro in Every Flight",
    shortDescription: "Foldable quadcopter with upgraded power system delivering 50kg payload. Features refined RevoSpray and RevoCast systems for breakthrough efficiency in spraying and spreading.",
    oemUrl: "https://xa.com/en/p100pro",
    highlights: ["50 kg max payload", "50 L smart tank", "80 L granule container", "13.8 m/s flight speed", "Foldable design", "Water cooling charging"],
    keyFeatures: ["RevoSpray3 system", "RevoCast3 spreading", "RealTerra 2 mapping", "4D imaging radar", "Swarm control", "11-min fast charge"],
    specs: ["Max Payload: 50 kg", "Max Flight Speed: 13.8 m/s", "Smart Liquid Tank: 50 L", "Max Flow Rate: 22 L/min", "Effective Spray Width: 5-10 m", "Granule Container: 80 L", "Max Spread Rate: 150 kg/min", "Open Field Efficiency: 19 ha/h"],
    worksWith: ["XAG One App", "ARC3 Pro Controller", "ACS2 Control Stick", "XRTK Base Station"],
    slug: "xag-p100-pro",
  },

  // Ag Leader Products
  {
    name: "InCommand Go",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Displays",
    tagline: "Year-round precision farming display",
    shortDescription: "Year-round display designed to keep map + real-time monitoring together with flexible on-screen tiles.",
    oemUrl: "https://www.agleader.com/incommand-go/",
    highlights: ["Year-round functionality", "Dynamic tiles", "Built-in connectivity"],
    keyFeatures: ["Year-round functionality", "Dynamic tiles", "Built-in connectivity options"],
    specs: [],
    worksWith: ["SteerCommand", "SureDrive", "DirectCommand"],
    slug: "agl-incommand-go",
  },
  {
    name: "SteerCommand Z2",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Machine Guidance",
    tagline: "Premium integrated guidance and steering",
    shortDescription: "All-in-one guidance controller with integrated steering capabilities.",
    oemUrl: "https://www.agleader.com/steercommand-z2/",
    highlights: ["Integrated steering", "High accuracy", "Easy installation"],
    keyFeatures: ["Integrated solution", "Premium performance"],
    specs: [],
    worksWith: ["InCommand", "InCommand Go"],
    slug: "agl-steercommand-z2",
  },
  {
    name: "SteadySteer",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Machine Guidance",
    tagline: "Hydraulic-assisted steering system",
    shortDescription: "Reliable hydraulic steering assist for precision guidance.",
    oemUrl: "https://www.agleader.com/steadysteer/",
    highlights: ["Hydraulic assist", "Proven reliability", "Wide compatibility"],
    keyFeatures: ["Hydraulic steering", "Universal fit"],
    specs: [],
    worksWith: ["InCommand displays", "SteerCommand"],
    slug: "agl-steadysteer",
  },
  {
    name: "TurnPath",
    brand: "Ag Leader",
    equipment: "Software Feature",
    category: "Features",
    tagline: "Automated turn guidance for all field activities",
    shortDescription: "TurnPath automates turns, improving precision and eliminating manual operation during turns. Benefits all field activities from tillage and planting to spraying and harvesting with easy calibration through InCommand/InCommand Go.",
    oemUrl: "https://www.agleader.com/turnpath/",
    highlights: ["Year-round solution for all operations", "Automatic turn guidance", "Easy setup and calibration", "Visual turn preview on display"],
    keyFeatures: ["Automated precision turning", "Multiple turn sequences", "Works with tillage, planting, application, harvest", "Generated guidance line for accurate approach"],
    specs: [
      "Requires InCommand or InCommand Go display",
      "Requires SteerCommand Z2 or SteadySteer",
      "Compatible with GPS 7500, 7000, 6500, or 6000",
      "Easily calibrate and adjust via display",
      "Multiple turn sequence options"
    ],
    worksWith: ["InCommand", "InCommand Go", "SteerCommand Z2", "SteadySteer"],
    slug: "agl-turnpath",
  },
  {
    name: "RightPath",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Features",
    tagline: "Proper implement placement for precise input placement",
    shortDescription: "RightPath ensures proper implement placement for precise input placement, increased operational efficiency, and minimized crop damage. Compatible with Ag Leader integrated and assisted steering systems for mixed fleets of new or older equipment.",
    oemUrl: "https://www.agleader.com/rightpath/",
    highlights: ["Maximize input placement on strip-till/NH3", "Consistent guess rows in all conditions", "Reduce operator stress and fatigue", "Reuse guidance lines for next operations"],
    keyFeatures: ["GPS on implement for true position", "View cross-track error for vehicle and implement", "Broad compatibility with mixed fleets", "Supports TerraStar-C Pro, TerraStar-X, or RTK"],
    specs: [
      "Requires InCommand Go 16 or InCommand Go 10",
      "Requires SteerCommand Z2 or SteadySteer",
      "Requires GPS 7500 with TerraStar-C Pro or better",
      "RightPath-unlocked GPS 7500 for implement",
      "RightPath cabling/bracket kit included"
    ],
    worksWith: ["InCommand Go 16", "InCommand Go 10", "SteerCommand Z2", "SteadySteer", "GPS 7500"],
    slug: "agl-rightpath",
  },
  {
    name: "SureForce",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Planter Products",
    tagline: "Active pneumatic downforce control",
    shortDescription: "Row-by-row pneumatic downforce for optimal seed placement.",
    oemUrl: "https://www.agleader.com/sureforce/",
    highlights: ["Row-by-row control", "Pneumatic system", "Optimal seed depth"],
    keyFeatures: ["Active downforce", "Real-time adjustment"],
    specs: [],
    worksWith: ["InCommand", "Most planters"],
    slug: "agl-sureforce",
  },
  {
    name: "SureSpeed",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Planter Products",
    tagline: "High-speed planting technology",
    shortDescription: "Enables high-speed planting while maintaining accuracy.",
    oemUrl: "https://www.agleader.com/surespeed/",
    highlights: ["High-speed planting", "Maintains accuracy", "Increased productivity"],
    keyFeatures: ["Speed optimization", "Accuracy maintenance"],
    specs: [],
    worksWith: ["SureDrive", "InCommand"],
    slug: "agl-surespeed",
  },
  {
    name: "SureDrive",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Planter Products",
    tagline: "Electric planter drive system",
    shortDescription: "Electric drives for planters using existing meters; supports row-by-row control, variable rate, and turn compensation.",
    oemUrl: "https://www.agleader.com/suredrive/",
    highlights: ["Electric drives", "Row-by-row control", "Variable rate seeding"],
    keyFeatures: ["Electric motors", "Turn compensation"],
    specs: ["2–90 RPM", "12V system", "6.2A max output", "4.5 Nm max torque"],
    worksWith: ["InCommand", "Most planter meters"],
    slug: "agl-suredrive",
  },
  {
    name: "SureStop",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Planter Products",
    tagline: "Lower seed cost, increase yield, increase productivity",
    shortDescription: "12V electric point row clutches eliminate double planting at end rows, point rows, and partial swaths to save seed and money. Ensures even spacing, reduces plant competition for increased yield, and eliminates the need to slow down at end rows.",
    oemUrl: "https://www.agleader.com/surestop/",
    highlights: ["Lower seed cost - eliminate double planting", "Increase yield with even spacing", "Increase productivity - no slowdown needed", "Rugged sealed design for durability"],
    keyFeatures: ["12V electric clutches on each row", "Individual or per-section shutoff wiring", "Mounts between hex shaft and seed meter", "Stops meter for previously planted areas"],
    specs: [
      "12V electric point row clutches",
      "Individual or per-section shutoff options",
      "Fits most popular brand planters",
      "Sealed design for year-after-year durability",
      "Mounts on row unit between hex shaft and seed meter"
    ],
    worksWith: ["InCommand", "InCommand Go", "Most popular planter brands"],
    slug: "agl-surestop",
  },
  {
    name: "RightSpot",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Applicator Products",
    tagline: "Individual nozzle control system",
    shortDescription: "Precision nozzle-by-nozzle spray control for optimal coverage.",
    oemUrl: "https://www.agleader.com/rightspot/",
    highlights: ["Nozzle-level control", "Reduced overlap", "Chemical savings"],
    keyFeatures: ["Individual nozzle control", "Precision application"],
    specs: [],
    worksWith: ["InCommand", "Sprayers"],
    slug: "agl-rightspot",
  },
  {
    name: "DirectCommand L2",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Applicator Products",
    tagline: "Section control up to 36 boom sections with variable rate",
    shortDescription: "Controls liquid applications, planters, sprayers, and NH3 applicators with up to 36 boom sections and variable-rate application. Easily upgradeable to RightSpot for nozzle-by-nozzle control when you're ready.",
    oemUrl: "https://www.agleader.com/directcommand-l2/",
    highlights: ["Up to 36 boom sections", "Variable rate application", "Droplet size monitoring", "Buildable path to RightSpot"],
    keyFeatures: ["Liquid, planter, sprayer, NH3 support", "High-resolution application mapping", "Real-time row-level stats on map", "Always accessible guidance and steering"],
    specs: [
      "Control up to 36 boom sections",
      "Variable-rate application capable",
      "Multi-application support (liquid, planter, sprayer, NH3)",
      "Droplet size monitoring included",
      "Easy upgrade path to RightSpot"
    ],
    worksWith: ["InCommand", "InCommand Go", "Sprayers", "Planters", "Liquid applicators", "NH3 applicators"],
    slug: "agl-directcommand-l2",
  },
  {
    name: "BoomLoop",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Applicator Products",
    tagline: "Fully-integrated recirculation solution with automated priming",
    shortDescription: "Paired with RightSpot, BoomLoop creates a streamlined path for product to flow from boom ends back to tank, eliminating dead spots and buildup. Automates priming to fill the entire boom without dispensing product to ground.",
    oemUrl: "https://www.agleader.com/boomloop/",
    highlights: ["Automated boom priming", "Eliminates dead spots and buildup", "Recirculate on-the-go while folded", "Convenient automatic sequencing"],
    keyFeatures: ["Fully-integrated recirculation", "Automatic priming process", "Automatic section valve sequencing", "Works with boom folded or unlevel"],
    specs: [
      "Fully-integrated recirculation solution",
      "Automated priming from tank to boom",
      "Automatic section valve sequencing",
      "View and control via InCommand display",
      "Visual and audio alerts when active"
    ],
    worksWith: ["RightSpot", "InCommand Go 16", "Sprayers"],
    slug: "agl-boomloop",
  },
  {
    name: "DirectCommand Granular",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Applicator Products",
    tagline: "Autoswath, variable rate, and easy reporting for granular applications",
    shortDescription: "Automatically turn the applicator on/off based on field boundaries and already-applied areas. Apply up to three products with variable rate and generate SmartReports with location, product information, and as-applied maps right from the display.",
    oemUrl: "https://www.agleader.com/granular/",
    highlights: ["AutoSwath reduces overapplication", "Variable rate for up to 3 products", "SmartReports from display", "Container sequencing for sequential application"],
    keyFeatures: ["Automatic on/off based on boundaries", "Variable rate prescription support", "Container sequencing for multiple containers", "Industry-leading visibility with InCommand"],
    specs: [
      "AutoSwath for automatic on/off",
      "Variable rate for up to 3 products",
      "Container sequencing support",
      "SmartReports with maps and totals",
      "InCommand display integration"
    ],
    worksWith: ["InCommand", "InCommand Go", "Spreaders", "Air seeders", "Strip-till applicators"],
    slug: "agl-granular",
  },

  // SurePoint Ag Products
  {
    name: "Sentinel",
    brand: "SurePoint Ag",
    equipment: "Hardware",
    category: "Liquid Control",
    tagline: "Advanced liquid control system",
    shortDescription: "Comprehensive liquid management for spray operations.",
    oemUrl: "https://www.surepointag.com/sentinel",
    highlights: ["Complete liquid control", "Real-time monitoring", "Operator-friendly"],
    keyFeatures: ["Liquid management", "Monitoring system"],
    specs: [],
    worksWith: ["Sprayers", "Tender systems"],
    slug: "sp-sentinel",
  },
  {
    name: "PumpRight",
    brand: "SurePoint Ag",
    equipment: "Hardware",
    category: "Liquid Control",
    tagline: "Precision pump control system",
    shortDescription: "Automated pump management for consistent performance.",
    oemUrl: "https://www.surepointag.com/pumpright",
    highlights: ["Pump automation", "Consistent flow", "Easy operation"],
    keyFeatures: ["Pump control", "Flow optimization"],
    specs: [],
    worksWith: ["Tender systems", "Sprayers"],
    slug: "sp-pumpright",
  },
  {
    name: "QuickDraw",
    brand: "SurePoint Ag",
    equipment: "Hardware",
    category: "Spray Tender",
    tagline: "Automated chemical mixing system",
    shortDescription: "Automated chemical mixing/loading workflow—enter acres or gallons and rates, and the system calculates batch amounts.",
    oemUrl: "https://www.surepointag.com/quickdraw",
    highlights: ["Automated mixing", "Accurate calculations", "Time savings"],
    keyFeatures: ["Batch calculation", "Automated loading"],
    specs: [],
    worksWith: ["Arsenal trailers", "Chemical systems"],
    slug: "sp-quickdraw",
  },
  {
    name: "ChemBlade",
    brand: "SurePoint Ag",
    equipment: "Hardware",
    category: "Spray Tender",
    tagline: "Container cutting and rinsing system",
    shortDescription: "Enclosed system to cut/rinse jugs (and handle certain dry products) to improve speed and operator safety.",
    oemUrl: "https://www.surepointag.com/chemblade",
    highlights: ["Enclosed operation", "Improved safety", "Faster processing"],
    keyFeatures: ["Container handling", "Rinse system"],
    specs: [],
    worksWith: ["Tender operations", "Chemical containers"],
    slug: "sp-chemblade",
  },
  {
    name: "Arsenal Spray Trailer + QuickDraw",
    brand: "SurePoint Ag",
    equipment: "Hardware",
    category: "Spray Tender",
    tagline: "Expertly designed, all-in-one, automated tendering system",
    shortDescription: "Purpose-built spray trailer designed with sprayer operators in mind for peak efficiency and safety. Includes modular loading deck with wings for QuickDraw cabinet and totes, swing-out load boom, swing-down stainless-steel eductor with ChemBlade, and Enduraplas tanks.",
    oemUrl: "https://www.surepointag.com/arsenal",
    highlights: ["Turnkey setup - ready to hit the field", "Ground-level operation reduces climbing risks", "QuickDraw automated spray tender included", "All carrier plumbing below deck for clean surface"],
    keyFeatures: ["Modular loading deck for flexible configuration", "Wings for QuickDraw cabinet and totes", "ChemBlade with swing-down stainless steel eductor", "Undermounted hose tray protects plumbing"],
    specs: [
      "Available lengths: 38', 42', or 48'",
      "Tank sizes: 2,800 gal or 3,200 gal Enduraplas tanks",
      "Load-out: Driver side or passenger side",
      "Loading device: Swing-out boom or 3\" hose reel",
      "Optional tote rack for storage",
      "Steps and handrail included",
      "Chemical rinse hose reel mounted"
    ],
    worksWith: ["QuickDraw", "ChemBlade", "Sentinel", "PumpRight"],
    slug: "sp-arsenal",
  },

  // Salford Products
  {
    name: "Endurance Spreader",
    brand: "Salford",
    equipment: "Implement",
    category: "Spreaders",
    tagline: "Heavy-duty spreader for demanding conditions",
    shortDescription: "Built tough for high-capacity fertilizer and lime spreading.",
    oemUrl: "https://salfordgroup.com/equipment/endurance-spreader/",
    highlights: ["Heavy-duty construction", "High capacity", "Reliable spreading"],
    keyFeatures: ["Durable design", "High tonnage"],
    specs: [],
    worksWith: ["Tractors", "Application control systems"],
    slug: "salford-endurance",
  },
  {
    name: "Grasshopper Spinner Spreader",
    brand: "Salford",
    equipment: "Implement",
    category: "Spreaders",
    tagline: "High-clearance top-dress spreader",
    shortDescription: "Pull-type top-dress applicator designed for row crop and turf; designed for fertilizer/lime with high clearance.",
    oemUrl: "https://salfordgroup.com/equipment/grasshopper-spinner-spreader/",
    highlights: ["High clearance", "Row crop friendly", "Precise spreading"],
    keyFeatures: ["Top-dress capability", "Turf compatible"],
    specs: [],
    worksWith: ["Row crop tractors", "Turf equipment"],
    slug: "salford-grasshopper",
  },
  {
    name: "MagnaSpread Spinner Spreader",
    brand: "Salford",
    equipment: "Implement",
    category: "Spreaders",
    tagline: "Multi-bin variable rate spreader",
    shortDescription: "Advanced multi-compartment spreader for variable rate applications.",
    oemUrl: "https://salfordgroup.com/equipment/magnaspread-spinner-spreader/",
    highlights: ["Multi-bin design", "Variable rate capable", "Precision application"],
    keyFeatures: ["Multiple compartments", "Independent control"],
    specs: [],
    worksWith: ["Variable rate controllers", "GPS systems"],
    slug: "salford-magnaspread",
  },
  {
    name: "Sniper Spinner Spreader",
    brand: "Salford",
    equipment: "Implement",
    category: "Spreaders",
    tagline: "Precision variable rate spinner spreader",
    shortDescription: "Advanced precision spreader with accurate variable rate control.",
    oemUrl: "https://salfordgroup.com/equipment/sniper-spinner-spreader/",
    highlights: ["Precision control", "Variable rate", "Accurate placement"],
    keyFeatures: ["High accuracy", "Rate control"],
    specs: [],
    worksWith: ["GPS systems", "Rate controllers"],
    slug: "salford-sniper",
  },

  // AMAZONE Products
  {
    name: "ZA-TS Mounted Spreader",
    brand: "AMAZONE",
    equipment: "Implement",
    category: "Spreaders (Mounted)",
    tagline: "High outputs with precise results - pure precision from one spreading unit",
    shortDescription: "Highly efficient fertilizer spreader with the innovative TS spreading system. Fertiliser is applied reliably, even in windy conditions or when fertiliser quality is poor, with working widths up to 54m and precise boundary spreading.",
    oemUrl: "https://amazone.net/en/products-digital-solutions/agricultural-technology/fertilising-technology/mounted-spreader/za-ts-mounted-spreader-51506",
    highlights: ["Up to 54m working width", "AutoTS border spreading", "WindControl wind compensation", "HeadlandControl headland optimization"],
    keyFeatures: ["TS spreading system for reliable patterns", "AutoTS and BorderTS boundary spreading", "ProfisPro rate calibration from first second", "ArgusTwin permanent spread fan monitoring"],
    specs: [
      "Working width: 15m to 54m",
      "Hopper capacity: 1,400L to 5,000L",
      "Up to 128 sections",
      "Mechanical or hydraulic spreading disc drive",
      "HeadlandControl headland optimization",
      "WindControl option for wind compensation",
      "ArgusTwin option for spread fan monitoring"
    ],
    worksWith: ["ISOBUS tractors", "Section control systems", "Variable rate controllers"],
    slug: "amazone-za-ts",
  },
  {
    name: "ZG-TX Trailed Combi Spreader",
    brand: "AMAZONE",
    equipment: "Implement",
    category: "Spreaders (Trailed)",
    tagline: "Flexible combination spreader for fertilizer and lime application",
    shortDescription: "AMAZONE sets new standards with the ZG-TX combi spreader. Apply granular mineral fertilisers and earth-moist limes precisely through one machine with simple conversion between the TS spreading system and the newly developed lime spreading unit.",
    oemUrl: "https://amazone.net/en/products-digital-solutions/agricultural-technology/fertilising-technology/trailed-spreader/zg-tx-trailed-combi-spreader-1453192",
    highlights: ["Quick fertilizer/lime conversion", "Perfect border spreading with AutoTS", "FlowControl precise rate regulation", "HeadlandControl for uniform headland crops"],
    keyFeatures: ["TS spreading system for precise patterns", "Newly developed lime spreading unit", "AutoTS for fertiliser boundary spreading", "Border spread deflector for lime precision"],
    specs: [
      "Working width: 15m to 54m",
      "Hopper capacity: 6,800L to 11,200L",
      "Up to 16 sections",
      "Mechanical spreading disc drive",
      "EasySet 2 in-cab terminal or ISOBUS compatible",
      "FlowControl for precise rate regulation",
      "HeadlandControl for uniform headland application"
    ],
    worksWith: ["ISOBUS tractors", "GPS guidance systems", "Variable rate controllers"],
    slug: "amazone-zg-tx",
  },
];

export function getProductBySlug(slug: string) {
  return catalogProducts.find(p => p.slug === slug);
}

export function getProductsByBrand(brand: string) {
  return catalogProducts.filter(p => p.brand === brand);
}

export function getProductsByCategory(category: string) {
  return catalogProducts.filter(p => p.category === category);
}

export function getAllBrands(): string[] {
  const brands = new Set<string>();
  catalogProducts.forEach(p => {
    if (p.brand) brands.add(p.brand);
  });
  return Array.from(brands);
}

export function getAllCategories(): string[] {
  const categories = new Set<string>();
  catalogProducts.forEach(p => categories.add(p.category));
  return Array.from(categories);
}