import type { InsertProduct } from "@shared/schema";

export const catalogProducts: Omit<InsertProduct, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // PTx Trimble Products
  {
    name: "GFX-1260 Display",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Displays",
    tagline: "Premium 12.1-inch display for precision agriculture operations",
    shortDescription: "Advanced 12.1-inch display for controlling and executing precision agriculture operations.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/displays/gfx-1260-display",
    highlights: ["Large 12.1-inch touchscreen", "Android-based platform", "Precision-IQ compatible"],
    keyFeatures: ["Android-based", "Precision-IQ platform", "High-definition display"],
    specs: [],
    worksWith: ["NAV-960", "NAV-500", "Autopilot systems"],
    slug: "ptx-gfx-1260",
  },
  {
    name: "GFX-1060 Display",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Displays",
    tagline: "10-inch Android-based display for precision agriculture",
    shortDescription: "10-inch Android-based display for controlling and executing operations using the Precision-IQ platform.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/displays/gfx-1060-display",
    highlights: ["Android-based", "Precision-IQ platform", "ISOBUS compatible"],
    keyFeatures: ["Android-based", "Precision-IQ platform"],
    specs: [
      "10-inch high-definition color touchscreen",
      "Android-based operating system",
      "Precision-IQ firmware",
      "32 GB storage / 4 GB RAM",
      "Optional ISOBUS task controller & universal terminal",
      "Control up to 6 input channels and 255 sections",
    ],
    worksWith: ["NAV-960", "NAV-500", "Field-IQ"],
    slug: "ptx-gfx-1060",
  },
  {
    name: "GFX-350 Display",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Displays",
    tagline: "Compact 7-inch display for essential guidance functions",
    shortDescription: "Entry-level display for basic guidance and application control.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/displays/gfx-350-display",
    highlights: ["Compact 7-inch screen", "Cost-effective solution", "Easy to use"],
    keyFeatures: ["Compact design", "Essential features"],
    specs: [],
    worksWith: ["EZ-Pilot Pro", "NAV-500"],
    slug: "ptx-gfx-350",
  },
  {
    name: "NAV-960 Guidance Controller",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Guidance Controllers",
    tagline: "High-accuracy GNSS guidance controller",
    shortDescription: "Premium guidance controller with centimeter-level accuracy.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/guidance-control/nav-960-guidance-controller",
    highlights: ["Centimeter-level accuracy", "Multi-constellation GNSS", "Integrated INS"],
    keyFeatures: ["High-accuracy positioning", "Integrated inertial system"],
    specs: [],
    worksWith: ["GFX-1260", "GFX-1060", "Autopilot"],
    slug: "ptx-nav-960",
  },
  {
    name: "NAV-500 Guidance Controller",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Guidance Controllers",
    tagline: "Reliable mid-range GNSS guidance controller",
    shortDescription: "Cost-effective guidance controller for precision agriculture.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/guidance-control/nav-500-guidance-controller",
    highlights: ["Reliable accuracy", "Multi-constellation support", "Affordable"],
    keyFeatures: ["Multi-constellation GNSS", "Reliable performance"],
    specs: [],
    worksWith: ["GFX-1060", "GFX-350", "EZ-Pilot Pro"],
    slug: "ptx-nav-500",
  },
  {
    name: "AG-392 Receiver",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Receivers",
    tagline: "Multi-frequency GNSS receiver for precision guidance",
    shortDescription: "High-performance receiver supporting multiple correction sources.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/guidance-control/ag-392-receiver",
    highlights: ["Multi-frequency tracking", "Multiple correction sources", "Reliable performance"],
    keyFeatures: ["Multi-frequency GNSS", "RTK capable"],
    specs: [],
    worksWith: ["GFX displays", "Guidance controllers"],
    slug: "ptx-ag-392",
  },
  {
    name: "R750 Modular GNSS Receiver",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Receivers",
    tagline: "Next-generation modular GNSS receiver",
    shortDescription: "Flexible modular receiver with advanced positioning capabilities.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/guidance-control/r750-modular-gnss-receiver",
    highlights: ["Modular design", "Future-proof technology", "High accuracy"],
    keyFeatures: ["Modular architecture", "Advanced GNSS tracking"],
    specs: [],
    worksWith: ["GFX displays", "NAV controllers"],
    slug: "ptx-r750",
  },
  {
    name: "Autopilot Automated Steering",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Steering Systems",
    tagline: "Full-featured automated steering system",
    shortDescription: "Complete hands-free steering solution for maximum productivity.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/steering-systems/autopilot-automated-steering",
    highlights: ["Hands-free operation", "Sub-inch accuracy", "All-terrain capability"],
    keyFeatures: ["Automated steering", "High precision"],
    specs: [],
    worksWith: ["NAV-960", "GFX-1260", "GFX-1060"],
    slug: "ptx-autopilot-automated",
  },
  {
    name: "Autopilot Motor Drive",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Steering Systems",
    tagline: "Motor-driven automated steering for older equipment",
    shortDescription: "Retrofit steering solution using motor-driven wheel control.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/steering-systems/autopilot-motor-drive",
    highlights: ["Retrofit compatible", "Easy installation", "Reliable performance"],
    keyFeatures: ["Motor-driven control", "Legacy equipment support"],
    specs: [],
    worksWith: ["NAV controllers", "GFX displays"],
    slug: "ptx-autopilot-motor-drive",
  },
  {
    name: "EZ-Pilot Pro Steering",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Steering Systems",
    tagline: "Affordable assisted steering solution",
    shortDescription: "Entry-level assisted steering for cost-conscious operations.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/steering-systems/ez-pilot-pro-steering",
    highlights: ["Affordable option", "Easy installation", "Reliable guidance"],
    keyFeatures: ["Assisted steering", "Budget-friendly"],
    specs: [],
    worksWith: ["GFX-350", "NAV-500"],
    slug: "ptx-ez-pilot-pro",
  },
  {
    name: "TrueTracker Implement Steering",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Steering Systems",
    tagline: "Active implement steering for perfect row alignment",
    shortDescription: "Keeps implements precisely on the guidance line regardless of field conditions.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/steering-systems/truetracker-implement-steering-system",
    highlights: ["Active implement control", "Reduces skips and overlaps", "Works on hillsides"],
    keyFeatures: ["Implement guidance", "Active steering"],
    specs: [],
    worksWith: ["Autopilot", "NAV-960"],
    slug: "ptx-truetracker",
  },
  {
    name: "Field-IQ Crop Input Control",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Application Control",
    tagline: "Complete crop input management system",
    shortDescription: "Manages flow and application to prevent overlap, control rate, monitor delivery/blockage, and automate spreading controls.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/flow-application-control/field-iq-crop-input-control-system",
    highlights: ["Section control", "Variable rate", "Blockage monitoring"],
    keyFeatures: ["Flow management", "Overlap prevention"],
    specs: [],
    worksWith: ["GFX displays", "Planters", "Sprayers"],
    slug: "ptx-field-iq-crop-input",
  },
  {
    name: "WeedSeeker 2 Spot Spray",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Application Control",
    tagline: "See-and-spray weed detection system",
    shortDescription: "Real-time weed detection and targeted application to reduce chemical use.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/flow-application-control/weedseeker-2-spot-spray-system",
    highlights: ["90% chemical savings", "Real-time detection", "Fallow field application"],
    keyFeatures: ["Optical sensing", "Targeted spraying"],
    specs: [],
    worksWith: ["Sprayers", "GFX displays"],
    slug: "ptx-weedseeker-2",
  },
  {
    name: "Field-IQ ISOBUS Liquid Control",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Application Control",
    tagline: "ISOBUS-compatible liquid application control",
    shortDescription: "Universal liquid control system with ISOBUS compatibility.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/flow-application-control/field-iq-isobus-liquid-control-system",
    highlights: ["ISOBUS compatible", "Universal connectivity", "Precise control"],
    keyFeatures: ["ISOBUS protocol", "Liquid application"],
    specs: [],
    worksWith: ["ISOBUS implements", "GFX displays"],
    slug: "ptx-field-iq-isobus-liquid",
  },
  {
    name: "WM-FieldForm",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Land Forming",
    tagline: "Precision land forming and leveling system",
    shortDescription: "Automated grade control for efficient land forming operations.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/land-forming/wm-fieldform",
    highlights: ["Automated grading", "Precision leveling", "Improved drainage"],
    keyFeatures: ["Grade control", "Land forming automation"],
    specs: [],
    worksWith: ["Scrapers", "Land planes"],
    slug: "ptx-wm-fieldform",
  },
  {
    name: "VerticalPoint RTK Grade Control",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Land Forming",
    tagline: "RTK-based grade control for land leveling",
    shortDescription: "High-precision RTK grade control for land forming applications.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/land-forming/verticalpoint-rtk-grade-control",
    highlights: ["RTK precision", "Vertical accuracy", "Real-time control"],
    keyFeatures: ["RTK positioning", "Grade control"],
    specs: [],
    worksWith: ["Land forming equipment", "GFX displays"],
    slug: "ptx-verticalpoint-rtk",
  },
  {
    name: "WM-Drain Solution",
    brand: "PTx Trimble",
    equipment: "Hardware",
    category: "Subsurface Drainage",
    tagline: "Complete subsurface drainage solution",
    shortDescription: "Integrated drainage installation guidance and control system.",
    oemUrl: "https://ptxtrimble.com/en/products/hardware/subsurface-drainage/wm-drain-solution",
    highlights: ["Precision installation", "Grade control", "Drainage planning"],
    keyFeatures: ["Drainage guidance", "Installation control"],
    specs: [],
    worksWith: ["Tile plows", "GFX displays"],
    slug: "ptx-wm-drain-solution",
  },
  {
    name: "FarmENGAGE",
    brand: "PTx Trimble",
    equipment: "Software",
    category: "Software",
    tagline: "Farm operations management platform",
    shortDescription: "Farm operations management software focused on fleet connectivity and operational control.",
    oemUrl: "https://www.ptxag.com/en/farmengage/",
    highlights: ["Fleet management", "Real-time monitoring", "Operations analytics"],
    keyFeatures: ["Fleet connectivity", "Operational control"],
    specs: [],
    worksWith: ["All PTx Trimble hardware"],
    slug: "ptx-farmengage",
  },

  // XAG Products
  {
    name: "P150 Max",
    brand: "XAG",
    equipment: "Drone",
    category: "Drones",
    tagline: "High-capacity agricultural drone",
    shortDescription: "Advanced agricultural drone for precision spraying and spreading operations.",
    oemUrl: "https://xa.com/en/p150max",
    highlights: ["Large payload capacity", "Precision spraying", "Autonomous operation"],
    keyFeatures: ["High capacity", "Precision application"],
    specs: [],
    worksWith: ["XAG ground control", "Cloud platforms"],
    slug: "xag-p150-max",
  },

  // Ag Leader Products
  {
    name: "InCommand Go",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Displays",
    tagline: "Year-round precision farming display",
    shortDescription: "Year-round display designed to keep map + real-time monitoring together with flexible on-screen tiles.",
    oemUrl: "https://www.agleader.com/incommand-go/",
    highlights: ["Year-round functionality", "Dynamic tiles", "Built-in connectivity"],
    keyFeatures: ["Year-round functionality", "Dynamic tiles", "Built-in connectivity options"],
    specs: [],
    worksWith: ["SteerCommand", "SureDrive", "DirectCommand"],
    slug: "agl-incommand-go",
  },
  {
    name: "SteerCommand Z2",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Machine Guidance",
    tagline: "Premium integrated guidance and steering",
    shortDescription: "All-in-one guidance controller with integrated steering capabilities.",
    oemUrl: "https://www.agleader.com/steercommand-z2/",
    highlights: ["Integrated steering", "High accuracy", "Easy installation"],
    keyFeatures: ["Integrated solution", "Premium performance"],
    specs: [],
    worksWith: ["InCommand", "InCommand Go"],
    slug: "agl-steercommand-z2",
  },
  {
    name: "SteadySteer",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Machine Guidance",
    tagline: "Hydraulic-assisted steering system",
    shortDescription: "Reliable hydraulic steering assist for precision guidance.",
    oemUrl: "https://www.agleader.com/steadysteer/",
    highlights: ["Hydraulic assist", "Proven reliability", "Wide compatibility"],
    keyFeatures: ["Hydraulic steering", "Universal fit"],
    specs: [],
    worksWith: ["InCommand displays", "SteerCommand"],
    slug: "agl-steadysteer",
  },
  {
    name: "TurnPath",
    brand: "Ag Leader",
    equipment: "Software Feature",
    category: "Features",
    tagline: "Automated end-of-row turns",
    shortDescription: "Automates end-of-row turns for hands-free, repeatable turning sequences via InCommand/InCommand Go.",
    oemUrl: "https://www.agleader.com/turnpath/",
    highlights: ["Hands-free turns", "Repeatable patterns", "Reduced operator fatigue"],
    keyFeatures: ["Automated turning", "Pattern memory"],
    specs: [],
    worksWith: ["InCommand", "InCommand Go", "SteerCommand"],
    slug: "agl-turnpath",
  },
  {
    name: "RightPath",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Features",
    tagline: "Passive implement guidance",
    shortDescription: "Passive implement steering to keep the implement centered on the guidance line.",
    oemUrl: "https://www.agleader.com/rightpath/",
    highlights: ["Implement centering", "Passive steering", "Reduced overlap"],
    keyFeatures: ["Implement guidance", "Passive control"],
    specs: [],
    worksWith: ["InCommand displays", "Row planters"],
    slug: "agl-rightpath",
  },
  {
    name: "SureForce",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Planter Products",
    tagline: "Active pneumatic downforce control",
    shortDescription: "Row-by-row pneumatic downforce for optimal seed placement.",
    oemUrl: "https://www.agleader.com/sureforce/",
    highlights: ["Row-by-row control", "Pneumatic system", "Optimal seed depth"],
    keyFeatures: ["Active downforce", "Real-time adjustment"],
    specs: [],
    worksWith: ["InCommand", "Most planters"],
    slug: "agl-sureforce",
  },
  {
    name: "SureSpeed",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Planter Products",
    tagline: "High-speed planting technology",
    shortDescription: "Enables high-speed planting while maintaining accuracy.",
    oemUrl: "https://www.agleader.com/surespeed/",
    highlights: ["High-speed planting", "Maintains accuracy", "Increased productivity"],
    keyFeatures: ["Speed optimization", "Accuracy maintenance"],
    specs: [],
    worksWith: ["SureDrive", "InCommand"],
    slug: "agl-surespeed",
  },
  {
    name: "SureDrive",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Planter Products",
    tagline: "Electric planter drive system",
    shortDescription: "Electric drives for planters using existing meters; supports row-by-row control, variable rate, and turn compensation.",
    oemUrl: "https://www.agleader.com/suredrive/",
    highlights: ["Electric drives", "Row-by-row control", "Variable rate seeding"],
    keyFeatures: ["Electric motors", "Turn compensation"],
    specs: ["2–90 RPM", "12V system", "6.2A max output", "4.5 Nm max torque"],
    worksWith: ["InCommand", "Most planter meters"],
    slug: "agl-suredrive",
  },
  {
    name: "SureStop",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Planter Products",
    tagline: "Individual row clutch system",
    shortDescription: "Row-by-row clutch control for precision seed placement.",
    oemUrl: "https://www.agleader.com/surestop/",
    highlights: ["Individual row control", "Eliminates overlap", "Seed savings"],
    keyFeatures: ["Row clutches", "Section control"],
    specs: [],
    worksWith: ["InCommand", "Planters"],
    slug: "agl-surestop",
  },
  {
    name: "RightSpot",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Applicator Products",
    tagline: "Individual nozzle control system",
    shortDescription: "Precision nozzle-by-nozzle spray control for optimal coverage.",
    oemUrl: "https://www.agleader.com/rightspot/",
    highlights: ["Nozzle-level control", "Reduced overlap", "Chemical savings"],
    keyFeatures: ["Individual nozzle control", "Precision application"],
    specs: [],
    worksWith: ["InCommand", "Sprayers"],
    slug: "agl-rightspot",
  },
  {
    name: "DirectCommand L2",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Applicator Products",
    tagline: "Liquid application control",
    shortDescription: "Complete liquid application control with section management.",
    oemUrl: "https://www.agleader.com/directcommand-l2/",
    highlights: ["Section control", "Rate control", "Application mapping"],
    keyFeatures: ["Liquid control", "Multi-product capable"],
    specs: [],
    worksWith: ["InCommand", "Sprayers", "Liquid applicators"],
    slug: "agl-directcommand-l2",
  },
  {
    name: "BoomLoop",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Applicator Products",
    tagline: "Boom recirculation system",
    shortDescription: "Keeps spray boom primed for instant-on application.",
    oemUrl: "https://www.agleader.com/boomloop/",
    highlights: ["Instant-on spraying", "No lag time", "Consistent application"],
    keyFeatures: ["Recirculation", "Prime maintenance"],
    specs: [],
    worksWith: ["Sprayers", "DirectCommand"],
    slug: "agl-boomloop",
  },
  {
    name: "DirectCommand Granular",
    brand: "Ag Leader",
    equipment: "Hardware",
    category: "Applicator Products",
    tagline: "Granular application control",
    shortDescription: "Granular application controls (autoswath, variable rate, reporting) through InCommand ecosystem.",
    oemUrl: "https://www.agleader.com/granular/",
    highlights: ["Autoswath", "Variable rate", "Integrated reporting"],
    keyFeatures: ["Granular control", "Variable rate capable"],
    specs: [],
    worksWith: ["InCommand", "Spreaders", "Air seeders"],
    slug: "agl-granular",
  },

  // SurePoint Ag Products
  {
    name: "Sentinel",
    brand: "SurePoint Ag",
    equipment: "Hardware",
    category: "Liquid Control",
    tagline: "Advanced liquid control system",
    shortDescription: "Comprehensive liquid management for spray operations.",
    oemUrl: "https://www.surepointag.com/sentinel",
    highlights: ["Complete liquid control", "Real-time monitoring", "Operator-friendly"],
    keyFeatures: ["Liquid management", "Monitoring system"],
    specs: [],
    worksWith: ["Sprayers", "Tender systems"],
    slug: "sp-sentinel",
  },
  {
    name: "PumpRight",
    brand: "SurePoint Ag",
    equipment: "Hardware",
    category: "Liquid Control",
    tagline: "Precision pump control system",
    shortDescription: "Automated pump management for consistent performance.",
    oemUrl: "https://www.surepointag.com/pumpright",
    highlights: ["Pump automation", "Consistent flow", "Easy operation"],
    keyFeatures: ["Pump control", "Flow optimization"],
    specs: [],
    worksWith: ["Tender systems", "Sprayers"],
    slug: "sp-pumpright",
  },
  {
    name: "QuickDraw",
    brand: "SurePoint Ag",
    equipment: "Hardware",
    category: "Spray Tender",
    tagline: "Automated chemical mixing system",
    shortDescription: "Automated chemical mixing/loading workflow—enter acres or gallons and rates, and the system calculates batch amounts.",
    oemUrl: "https://www.surepointag.com/quickdraw",
    highlights: ["Automated mixing", "Accurate calculations", "Time savings"],
    keyFeatures: ["Batch calculation", "Automated loading"],
    specs: [],
    worksWith: ["Arsenal trailers", "Chemical systems"],
    slug: "sp-quickdraw",
  },
  {
    name: "ChemBlade",
    brand: "SurePoint Ag",
    equipment: "Hardware",
    category: "Spray Tender",
    tagline: "Container cutting and rinsing system",
    shortDescription: "Enclosed system to cut/rinse jugs (and handle certain dry products) to improve speed and operator safety.",
    oemUrl: "https://www.surepointag.com/chemblade",
    highlights: ["Enclosed operation", "Improved safety", "Faster processing"],
    keyFeatures: ["Container handling", "Rinse system"],
    specs: [],
    worksWith: ["Tender operations", "Chemical containers"],
    slug: "sp-chemblade",
  },
  {
    name: "Arsenal Spray Trailer",
    brand: "SurePoint Ag",
    equipment: "Hardware",
    category: "Spray Tender",
    tagline: "Purpose-built spray tender trailer",
    shortDescription: "Purpose-built spray trailer platform (multiple lengths) designed for efficiency and safety.",
    oemUrl: "https://www.surepointag.com/arsenal",
    highlights: ["Multiple configurations", "Built for efficiency", "Safety focused"],
    keyFeatures: ["Complete tender platform", "Modular design"],
    specs: [],
    worksWith: ["QuickDraw", "ChemBlade", "Sentinel"],
    slug: "sp-arsenal",
  },

  // Salford Products
  {
    name: "Endurance Spreader",
    brand: "Salford",
    equipment: "Implement",
    category: "Spreaders",
    tagline: "Heavy-duty spreader for demanding conditions",
    shortDescription: "Built tough for high-capacity fertilizer and lime spreading.",
    oemUrl: "https://salfordgroup.com/equipment/endurance-spreader/",
    highlights: ["Heavy-duty construction", "High capacity", "Reliable spreading"],
    keyFeatures: ["Durable design", "High tonnage"],
    specs: [],
    worksWith: ["Tractors", "Application control systems"],
    slug: "salford-endurance",
  },
  {
    name: "Grasshopper Spinner Spreader",
    brand: "Salford",
    equipment: "Implement",
    category: "Spreaders",
    tagline: "High-clearance top-dress spreader",
    shortDescription: "Pull-type top-dress applicator designed for row crop and turf; designed for fertilizer/lime with high clearance.",
    oemUrl: "https://salfordgroup.com/equipment/grasshopper-spinner-spreader/",
    highlights: ["High clearance", "Row crop friendly", "Precise spreading"],
    keyFeatures: ["Top-dress capability", "Turf compatible"],
    specs: [],
    worksWith: ["Row crop tractors", "Turf equipment"],
    slug: "salford-grasshopper",
  },
  {
    name: "MagnaSpread Spinner Spreader",
    brand: "Salford",
    equipment: "Implement",
    category: "Spreaders",
    tagline: "Multi-bin variable rate spreader",
    shortDescription: "Advanced multi-compartment spreader for variable rate applications.",
    oemUrl: "https://salfordgroup.com/equipment/magnaspread-spinner-spreader/",
    highlights: ["Multi-bin design", "Variable rate capable", "Precision application"],
    keyFeatures: ["Multiple compartments", "Independent control"],
    specs: [],
    worksWith: ["Variable rate controllers", "GPS systems"],
    slug: "salford-magnaspread",
  },
  {
    name: "Sniper Spinner Spreader",
    brand: "Salford",
    equipment: "Implement",
    category: "Spreaders",
    tagline: "Precision variable rate spinner spreader",
    shortDescription: "Advanced precision spreader with accurate variable rate control.",
    oemUrl: "https://salfordgroup.com/equipment/sniper-spinner-spreader/",
    highlights: ["Precision control", "Variable rate", "Accurate placement"],
    keyFeatures: ["High accuracy", "Rate control"],
    specs: [],
    worksWith: ["GPS systems", "Rate controllers"],
    slug: "salford-sniper",
  },

  // AMAZONE Products
  {
    name: "ZA-TS Mounted Spreader",
    brand: "AMAZONE",
    equipment: "Implement",
    category: "Spreaders (Mounted)",
    tagline: "Professional mounted fertilizer spreader",
    shortDescription: "High-performance mounted spreader for precise fertilizer distribution.",
    oemUrl: "https://amazone.net/en/products-digital-solutions/agricultural-technology/fertilising-technology/mounted-spreader/za-ts-mounted-spreader-51506",
    highlights: ["Professional grade", "Precise distribution", "Easy calibration"],
    keyFeatures: ["Mounted design", "High precision"],
    specs: [],
    worksWith: ["Tractors", "Section control systems"],
    slug: "amazone-za-ts",
  },
  {
    name: "ZG-TX Trailed Combi Spreader",
    brand: "AMAZONE",
    equipment: "Implement",
    category: "Spreaders (Trailed)",
    tagline: "High-capacity trailed combination spreader",
    shortDescription: "Large-scale trailed spreader for high-capacity operations.",
    oemUrl: "https://amazone.net/en/products-digital-solutions/agricultural-technology/fertilising-technology/trailed-spreader/zg-tx-trailed-combi-spreader-1453192",
    highlights: ["High capacity", "Trailed design", "Multi-product capable"],
    keyFeatures: ["Large hopper", "Combination spreading"],
    specs: [],
    worksWith: ["Large tractors", "GPS guidance"],
    slug: "amazone-zg-tx",
  },
];

export function getProductBySlug(slug: string) {
  return catalogProducts.find(p => p.slug === slug);
}

export function getProductsByBrand(brand: string) {
  return catalogProducts.filter(p => p.brand === brand);
}

export function getProductsByCategory(category: string) {
  return catalogProducts.filter(p => p.category === category);
}

export function getAllBrands(): string[] {
  const brands = new Set<string>();
  catalogProducts.forEach(p => {
    if (p.brand) brands.add(p.brand);
  });
  return Array.from(brands);
}

export function getAllCategories(): string[] {
  const categories = new Set<string>();
  catalogProducts.forEach(p => categories.add(p.category));
  return Array.from(categories);
}